version: '3.8'
services:
  app:
    build: .
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - db
      - logstash
    networks:
      - app-network
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.3
    environment:
      discovery.type: single-node
      xpack.security.enabled: false
    networks:
      - app-network

  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.3
    volumes:
      - ./elk:/usr/share/logstash/pipeline
    ports:
      - "5000:5000"
    networks:
      - app-network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.3
    ports:
      - "5601:5601"
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:

